# Generated by Django 2.2.7 on 2019-11-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191114_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_posted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Sub'),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
