# Generated by Django 2.2.7 on 2019-11-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191115_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_posted_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.Sub'),
        ),
    ]
